server:
  port: 8888
spring:
  application:
    name: reto-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PedroPoole/configs.git
          search-paths:
            - '*service*'
        
          
        default-label: main